Yelp/bravado-core

- CHANGELOG.rst
- bravado_core/spec.py
- bravado_core/unmarshal.py
- tests/unmarshal/unmarshal_schema_object_test.py
> Add use_models config option

- CHANGELOG.rst
- bravado_core/__init__.py
- bravado_core/spec.py
- docs/source/changelog.rst
- tests/spec/Spec/get_op_for_request_test.py
- tox.ini
See https://github.com/striglia/pyramid_swagger/issues/115
> Use basePath when matching a request to an operation

- CHANGELOG.rst
- bravado_core/response.py
- tests/response/IncomingResponse_test.py
- tests/response/unmarshal_response_test.py
Completing simple TODO to rename this class.  Associated PR for bravado is https://github.com/Yelp/bravado/pull/149
> Rename ResponseLike to IncomingResponse for consistency

- bravado_core/docstring.py
- tests/docstring/create_operation_docstring_test.py
Fix for unicode docstrings in issue #25.
> Handle unicode docstrings

- bravado_core/param.py
- tests/param/marshal_param_test.py
Verified with an actual http server!
> Fix unicode request path params

- CHANGELOG.rst
- bravado_core/model.py
- tests/model/create_model_docstring_test.py
> Fix unicode in model docstrings

- CHANGELOG.rst
- bravado_core/response.py
- tests/response/IncomingResponse_test.py
So `str(IncomingResponse)` contains useful info.
> Add reason to IncomingResponse

- CHANGELOG.rst
- bravado_core/__init__.py
- bravado_core/model.py
- bravado_core/spec.py
- test-data/2.0/simple/swagger.json
- test-data/2.0/simple_crossref/definitions/pingpong.json
- test-data/2.0/simple_crossref/operations/pingpong.json
- test-data/2.0/simple_crossref/parameters/pingpong.json
- test-data/2.0/simple_crossref/paths/pingpong.json
- test-data/2.0/simple_crossref/responses/pingpong.json
- test-data/2.0/simple_crossref/swagger.json
- tests/spec/from_dict_test.py
> Send absolute url ie origin_url to jsonref

- bravado_core/param.py
- tests/param/unmarshal_param_test.py
> Fix validation on non string multi collection

- bravado_core/operation.py
- tests/operation/operation_id_test.py
> Sanitize operationId

- tests/marshal/marshal_object_test.py
- tests/unmarshal/unmarshal_object_test.py
- tests/validate/validate_object_test.py
> Unit tests for marshal/unmarshal/validate property with no schema

- bravado_core/param.py
- bravado_core/swagger20_validator.py
- tests/param/unmarshal_param_test.py
- tests/swagger20_validator/enum_validator_test.py
- tests/validate/validate_object_test.py
> Fix request params that are optional enums

- bravado_core/swagger20_validator.py
- tests/swagger20_validator/enum_validator_test.py
- tests/swagger20_validator/required_validator_test.py
- tests/swagger20_validator/type_validator_test.py
- tests/validate/validate_primitive_test.py
> Fix validators to conform to generator functions

- README.rst
> Update README to reference OpenAPI instead of Swagger.

- bravado_core/resource.py
- tests/resource/build_resources_test.py
This is on top of #95 and adds a test.
> Fix path level vendor extensions

- requirements-dev.txt
"Unit test dependencies" at the top of the file
> Remove prod deps from requirements-dev.txt

- .gitignore
- .travis.yml
- Makefile
- requirements-dev.txt
- tests/profiling/conftest.py
- tox.ini
The goal of this PR is:
* simplify extendability of profiling related tests
* execute profiling on travis in order to keep periodic performance data for future comparisons
* make profiling data available (through termbin.com) if profiling test executed on travis
> Profiling improvements

- bravado_core/validate.py
- docs/source/models.rst
- tests/validate/validate_array_test.py
- tests/validate/validate_object_test.py
- tests/validate/validate_primitive_test.py
This will check against a new extension 'x-sensitive' and scrub the
value from the raised jsonschema.ValidationError if validation fails.
This addresses #209. All of the tests pass locally for me, and if we're satisfied with the approach, I'll add a test for the x-sensitive case.
> Add a try/except to the validation

- docs/source/index.rst
> Add link to swagger 2.0 specs in documentation

- bravado_core/param.py
- tests/param/marshal_param_test.py
> Make sure spaces are quoted as %20 in path params

- bravado_core/spec.py
- tests/conftest.py
While working on https://github.com/striglia/pyramid_swagger/pull/237 I did notice that bravado-core is not perfect on windows.
The goal of this PR is to fix this
> Support windows paths

- bravado_core/_compat_typing.py
- tests/param/get_param_type_spec_test.py
- tests/validate/validate_array_test.py
I suggest turning github branch protection on (to require passing tests in PRs) so that master doesn't get broken again.
> fix the tests

- .appveyor.yml
- .travis.yml
- setup.py
Minor cleanup from removal of python3.5 support
> Cleanup stragglers from removal of python3.5 support in PR #366
