- bravado_core/param.py
- bravado_core/spec.py
- tests/param/marshal_param_test.py
- tests/param/unmarshal_param_test.py
- tests/spec/Spec/__init__.py
- tests/spec/Spec/build_test.py
- tests/spec/__init__.py
- tests/spec/build_api_serving_url_test.py
Pretty self explanatory. Adding to support toggles in pyramid-swagger.
> Add config toggles for request validation and swagger spec validation

- bravado_core/spec.py
- tests/spec/Spec/get_op_for_request_test.py
Server-side impls will use to easily map an incoming request to an operation in the swagger spec.
> Allow lookup of an operation given request method and path

- bravado_core/spec.py
- tests/spec/replace_jsonref_proxies_test.py
Fixes compatibility problems with python 2.7 and other 3rd party json libraries that can't handle `JsonRef` objects.
> Replace jsonref proxies

- bravado_core/docstring.py
- bravado_core/exception.py
- bravado_core/marshal.py
- bravado_core/operation.py
- bravado_core/spec.py
- bravado_core/unmarshal.py
- tests/marshal/marshal_array_test.py
- tests/marshal/marshal_model_test.py
- tests/marshal/marshal_object_test.py
- tests/marshal/marshal_primitive_test.py
- tests/operation/construct_params_test.py
- tests/spec/build_api_serving_url_test.py
- tests/unmarshal/unmarshal_array_test.py
- tests/unmarshal/unmarshal_model_test.py
- tests/unmarshal/unmarshal_object_test.py
- tests/unmarshal/unmarshal_primitive_test.py
Fix for #19 
Base exception class is SwaggerError.
- SwaggerMappingError thrown when processing requests/responses
- SwaggerSchemaError thrown when processing the schema
I'll have follow up PRs for bravado and pyramid-swagger based on the change in the exception interface.
> Refactor exception hierarchy

- CHANGELOG.rst
- bravado_core/model.py
- tests/model/create_model_repr_test.py
- tests/model/create_model_type_test.py
Fixes errors like this when printing a model type:
```
Traceback (most recent call last):
File "test20.py", line 43, in <module>
print svc.media.getPhotos(business_id=1, photo_ids='1,2,3').result()
File "/nail/home/spatel/git/bravado-core-analogue/bravado_core/model.py", line 51, in <lambda>
__repr__=lambda self: create_model_repr(self, model_spec),
File "/nail/home/spatel/git/bravado-core-analogue/bravado_core/model.py", line 138, in create_model_repr
for attr_name in sorted(model_spec['properties'].keys())
File "/nail/home/spatel/git/bravado-core-analogue/bravado_core/model.py", line 51, in <lambda>
__repr__=lambda self: create_model_repr(self, model_spec),
File "/nail/home/spatel/git/bravado-core-analogue/bravado_core/model.py", line 138, in create_model_repr
for attr_name in …
```
> Fix model __repr__ wrt unicode attr values

- CHANGELOG.rst
- bravado_core/__init__.py
- bravado_core/param.py
- tests/param/add_file_test.py
- tests/param/marshal_param_test.py
This was a fun one to track down...
File uploads with curl on the client side and pyramid-swagger using Swagger 2.0 on the server side worked wonderfully. However, when using the bravado Swagger 2.0 client, I would get HTTP 500s as a response.
Working cURL dump of the form data for the file upload:
```
Content-Type: multipart/form-data; boundary=----------------------------e07d5bf53061
Content-Disposition: form-data; name="photo_file"; filename="test.jpg" Content-Type: image/jpeg JFIF...
```
Broken bravado dump:
```
Content-Type: multipart/form-data; boundary=-----------------------6e1996f15f14b6ab0ada267478ea560\r\n
Content-Disposition: form-data; name="file"; filename="photo_file"\r\n\r\n
\xff\xd8\xff\xe0\x00\x10JFIF...
```
"name" was incorrectly set to "file" instead of the name of the …
> Fix file uploads when marshaling a request; Bump to 1.0.0-rc2

- .travis.yml
- bravado_core/docstring.py
- bravado_core/formatter.py
- bravado_core/marshal.py
- bravado_core/model.py
- bravado_core/operation.py
- bravado_core/param.py
- bravado_core/request.py
- bravado_core/resource.py
- bravado_core/response.py
- bravado_core/spec.py
- bravado_core/unmarshal.py
- setup.py
- tests/formatter/register_format_test.py
- tests/formatter/to_python_test.py
- tests/formatter/to_wire_test.py
- tests/model/model_constructor_test.py
- tests/param/marshal_collection_format_test.py
- tests/param/unmarshal_collection_format_test.py
- tests/print_test.py
- tox.ini
This is ready once Julian/jsonschema#203 is in a release. Until then there's a bit of test flakiness for py3.
Fixes #10
> Support py3

- tests/marshal/marshal_object_test.py
- tests/marshal/marshal_primitive_test.py
- tests/unmarshal/unmarshal_object_test.py
- tests/unmarshal/unmarshal_primitive_test.py
While trying to reproduce the unicode in response body failure in #25, I added a bunch of tests.  No change in functionality.
> More unicode tests

- bravado_core/exception.py
- bravado_core/formatter.py
- bravado_core/validate.py
- tests/conftest.py
- tests/exception/wrap_exception_test.py
- tests/formatter/get_format_test.py
- tests/formatter/register_format_test.py
- tests/formatter/to_python_test.py
- tests/formatter/to_wire_test.py
- tests/param/cast_request_param_test.py
- tests/validate/validate_user_format_test.py
- add `SwaggerFormat` namedtuple
- add call to `validate` during primitive check
- Fixes #32
> Support and validation for user defined Swagger formats

- CHANGELOG.rst
- bravado_core/exception.py
- bravado_core/response.py
- tests/response/get_response_spec_test.py
Needed for https://github.com/Yelp/bravado/issues/153
> Use a more specific exception when a response can't be mapped to the schema

- bravado_core/spec.py
- tests/spec/replace_jsonref_proxies_test.py
- Fixes #40
- Dereference from dict was happening but not from list.
- If `assert not isinstance(json_obj['foo'][0], jsonref.JsonRef)` was added at L93 to `tests/spec/replace_jsonref_proxies_test.py`, it would fail. It passes now.
> Dereference elements from a list. Fixes #40.

- CHANGELOG.rst
- bravado_core/spec.py
- docs/source/config.rst
- docs/source/formats.rst
- docs/source/index.rst
- docs/source/models.rst
Subtle change from previous udf branch - formats are registered via the config dict passsed to `Spec.from_dict(spec_dict, config)` instead of calling `spec.register_format(....)` directly.  Much nicer flow from bravado since the config dict is just passed through from `bravado.client.SwaggerClient`.
> Docs on how to use user-defined formats and configure bravado-core

- CHANGELOG.rst
- bravado_core/resource.py
- tests/resource/build_resources_test.py
Builds on PR #56 by adding a unit test.
> Don't create an operation out of path parameters (with unit test)

- CHANGELOG.rst
- bravado_core/param.py
- bravado_core/unmarshal.py
- tests/param/unmarshal_collection_format_test.py
- tests/param/unmarshal_param_test.py
From @tomelm 
Unmarshalling fails when the below parameter is not present in the request's query string
```
http://foo.com/search/v1?term=burrito&location=sf
```
```json
{
"name": "categories",
"description": "The categories to filter on",
"in": "query",
"required": false,
"type": "array",
"items": {
"name": "category",
"type": "string"
}
},
```
```json
{
"traceback": [
"Traceback (most recent call last):\n",
"  File \"/nail/home/telmalem/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/pyramid/tweens.py\", line 21, in excview_tween\n    response = handler(request)\n",
"  File \"/nail/home/telmalem/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/pyramid_swagger/tween.py\", line 170, in validator_tween\n    validation_context=validation_context)\n",
"  File …
```
> Fix for unmarshalling array query param that is optional

- tests/param/unmarshal_param_test.py
`test_optional_query_string_with_default` implies that the param is optional, previously the param string was described as `string_param_spec['required'] = True` it seems to me that it should actually be `False`.
> Updated test so that behavior reflects its name

- bravado_core/param.py
- tests/param/cast_request_param_test.py
- tests/param/unmarshal_param_test.py
This closes the issue I opened, #68
> Gracefully handle empty quotes for ints, floats, and booleans

- bravado_core/schema.py
- tests/marshal/marshal_schema_object_test.py
The `is_dict_like` function in `schema.py` was just checking if the
object's type was a dict.  This causes it to treat any dict subclass as
a model, which fails because dict subclasses are not models.
Updating to check if the item is an instance of `collections.Mapping`
(or `collections.abc.Mapping` on python 3) fixes this.
> Add support for marshalling dict-like objects.

- bravado_core/spec.py
- tests/spec/strip_xscope_test.py
Fix for #78 
Server-side libraries that use bravado-core (such as pyramid-swagger) now have access to the Swagger spec in dict form without the internally attached x-scope metadata.
```python
spec = Spec.from_dict(spec_dict)
print spec.client_spec_dict
```
Given the options available, this bubbled up as the most straight-forward way to maintain backward compatibility, retain the mutability necessary to tag models, and provide server-side libraries access to the stripping behavior for subsequent remote $ref requests via ``bravado_core.spec.strip_xscope``.
Tested with example_happyhour (a single line change was necessary to pyramid_swagger - will submit PR after this is merged and released).
> Make spec_dict available without internal x-scope metadata

- CHANGELOG.rst
- bravado_core/swagger20_validator.py
- tests/swagger20_validator/ref_validator_test.py
Fixes #82, closes #83.
Created a second PR based on the fix by @analogue. The only change is fixing and enabling the second test. I verified internally that our service works with this fix. Your change lg2m, thumbs up from me for merging this.
> Use x-scope annotations when resolving refs during request/response validation

- CHANGELOG.rst
- bravado_core/param.py
- tests/param/marshal_param_test.py
- tox.ini
Fix for https://github.com/Yelp/bravado/issues/202
> Fix marshalling optional array query parameter when not passed in service call

- bravado_core/param.py
- tests/request/unmarshal_request_test.py
This patch is motivated by a situation I encountered using pyramid_swagger: when the user sends a request with invalid (or no) JSON, the ValueError from attempting to deserialize the request body is untrapped, leading to a 500 error. Ideally, this should be a 400 error, since the problem is that the request is incorrectly formatted, not that the server encountered an unexpected problem.  Trapping the ValueError raised by JSON translation and re-raising it as a more specific error is one way of accomplishing that.
It is possible that this behavior actually represents a bug in the pyramid_swagger IncomingRequest implementation, but the definition of the `json` method in IncomingRequest does not seem to specify any specific error handing behavior, so it's not clear to me what the appropriate …
> Convert ValueErrors from JSON reading to SwaggerMappingErrors.

- setup.py
- tests/unmarshal/unmarshal_primitive_test.py
- tests/validate/validate_primitive_test.py
Added tests for datetime parsing and validation, including a test that  should fail but does not with the current jsonschema dependency, then updated the jsonschema dependency to include the "format" option, which brings in the necessary additional libraries to make that validation run correctly.
This is an implementation of the solution proposed in #88: if that proposal is unacceptable, this PR will presumably also be unacceptable.
> Fixed jsonschema dependency to allow date-time validation.

- CHANGELOG.rst
- bravado_core/__init__.py
- tox.ini
This will fix an OSError while running flake8 in our Jenkins cluster.
> Add basepython python2.7 to all tox envs

- bravado_core/schema.py
- bravado_core/swagger20_validator.py
- tests/schema/is_prop_nullable_test.py
- tests/swagger20_validator/type_validator_test.py
- tests/unmarshal/unmarshal_nullable_test.py
Proposal for solving #47
The Swagger specification in version 2 doesn't support 'null' as
property value. This adds a vendor extension 'x-nullable' which
allows properties to be 'null' if set to 'true'.
> Allow null option for properties

- requirements-dev.txt
This fixes a test failure in ``test_string_datetime_invalid_exception`` I've been encountering on macOS, where neither package was installed by tox.
> Make sure jsonschema can parse and validate datetimes

- bravado_core/__init__.py
- bravado_core/unmarshal.py
- tests/unmarshal/unmarshal_schema_object_test.py
Right now it just raises a `KeyError`, which is difficult to understand. For example here are the relevant portions of the stack trace:
```python
[cut 42 lines...]
File "/nail/home/wting/code/services/public_api/.tox/py27/local/lib/python2.7/site-packages/bravado/http_future.py", line 77, in result
self.response_callbacks)
File "/nail/home/wting/code/services/public_api/.tox/py27/local/lib/python2.7/site-packages/bravado/http_future.py", line 115, in unmarshal_response
operation)
File "/nail/home/wting/code/services/public_api/.tox/py27/local/lib/python2.7/site-packages/bravado_core/response.py", line 110, in unmarshal_response
op.swagger_spec, content_spec, content_value)
File "/nail/home/wting/code/services/public_api/.tox/py27/local/lib/python2.7/site-packages/bravado_core/unmarshal.py" …
```
> Raise an exception when the required type field is missing for an schema_object_spec.

- bravado_core/exception.py
- tests/exception/wrap_exception_test.py
Currently methods decorated with wrap_exception will be called but their result is not returned hence making it impossible to get and further work with a wrap_exception decorated method.
In this pull request I‘m adding the `return` statement + a test case.
> Return methods return value instead of None

- bravado_core/param.py
- tests/param/unmarshal_param_test.py
Hey there!
I use pyramid_swagger, which relies on bravado-core. pyramid_swagger converts primitives when it can, which happens before it ends up calling bravado-core's `unmarshal_request`.
An issue I ran into today is essentially the test I've included with this change. I have a query parameter of a boolean type and by the time pyramid_swagger sends it to bravado_core for unmarshalling, the boolean is already a Python-bool and not a string-bool (i.e. 'true'), which causes `string_to_boolean` to raise a `ValueError`.
This change checks to see if a value passed into `string_to_boolean` is of type `bool` before treating it like a string.
I think it makes sense to fix this issue in this project so people who build on top of this can send Python bools if they want (which seems reasonable?). …
> Check if parameter value is a bool-type before assuming it's a string

- .gitignore
- bravado_core/marshal.py
- bravado_core/param.py
- bravado_core/schema.py
- bravado_core/unmarshal.py
- tests/marshal/marshal_array_test.py
- tests/marshal/marshal_model_test.py
- tests/marshal/marshal_object_test.py
- tests/marshal/marshal_primitive_test.py
- tests/param/marshal_param_test.py
- tests/unmarshal/unmarshal_model_test.py
- tests/unmarshal/unmarshal_object_test.py
This is the proposed fix for https://github.com/Yelp/bravado-core/issues/108
I updated unmarshal to better handle x-nullable properties and added additional test cases to cover the changes.
There are a number of remaining issues which I would prefer to leave for someone else to address:
- Unmarshalling of required non-nullable arrays works when it probably shouldn't (existing behavior)
- I had to make a copy of the dereferenced property specification dictionary to add in the x-nullable flag if present. My experience with serde in the past is that I often needed to pass the property specification in addition to the referenced type information. I chose not to do that here for expediency. The extra dictionary copy could be optimized by refactoring the code to do so.
> Fix to marshalling to better handle x-nullable and required properties

- bravado_core/param.py
- tests/param/unmarshal_collection_format_test.py
We've observed AttributeErrors internally if a required parameter of type array is not passed, instead of the expected schema or validation exception. This is because validation happens after unmarshalling of the array, and a missing required parameter is not currently handled correctly during unmarshalling.
> Fix AttributeError if required array param is not supplied

- bravado_core/param.py
- tests/param/marshal_param_test.py
The current implementation of the ``bravado-core`` causes troubles if you inject in the header a type that is different from a string or byte.
An example is available on [Gist](https://gist.github.com/macisamuele/5dc3874509135b1ddb16a906b4e50f99).
Checking the stack trace was possible to understand that the ``requests`` python library is checking the type of the header parameters ensuring that them are string or bytes.
Many similar issues are highlighted on the ``requests`` project, ie. [Issue #3477](https://github.com/kennethreitz/requests/issues/3477).
Due to the implementation of the [``check_header_validity``](https://github.com/kennethreitz/requests/blob/master/requests/utils.py#L782) is clear that we cannot pass any primitive type, as header parameter, to the ``requests`` module. …
> Cast to string the headers parameters

- bravado_core/model.py
- tests/model/conftest.py
- tests/model/create_model_type_test.py
Add marshal and unmarshal functionality, so we can deserialize and serialize easily in frontend services.
Same as this PR - https://github.com/Yelp/bravado-core/pull/113  But, I added tests, and found the unmarshal lambda function needed to be wrapped with staticmethod for python 2.6 and 2.7.  Otherwise, I'd get "TypeError: unbound method <lambda>()..."
> Add marshal and unmarshal to bravado-core.model's and testing

- CHANGELOG.rst
- README.rst
As done in [bravado](https://github.com/Yelp/bravado) could be helpful having a sort of guideline for the project contribution.
The CHANGELOG-MASTER.rst file is added in order to avoid to have the changelog related to the master modifications on readthedocs.
> Contribution guidelines and master changelog

- bravado_core/operation.py
- tests/operation/conftest.py
- tests/operation/security_object_test.py
Currently the global `security` property of the spec can be overridden in specific operations, but only if the list of security requirements is non-empty.
In the [official spec](http://swagger.io/specification/#operationObject) it states that
>  To remove a top-level security declaration, an empty array can be used
for an operation's `security` property.
This change should bring things in line with the official spec.
> Allow overriding security spec with empty list

- CHANGELOG.rst
- bravado_core/response.py
- tests/response/validate_response_body_test.py
Does not validate their body  in any meaningful way, but allows
us to take advantage of all the other request/response validations.
Main use case for us is defining some mandatory endpoints that cannot be implemented as `application/json` because of external requirements. For example:
```yaml
/metrics:
get:
produces:
- "text/plain"
responses:
"200":
description: "Prometheus metrics"
schema: 
type: string
```
> Adds minimal support for responses with text/* content_types

- CHANGELOG.rst
- bravado_core/model.py
- bravado_core/unmarshal.py
- tests/unmarshal/unmarshal_object_test.py
This adds support for models to contain properties named "self", without
triggering a name clash in the `__init__` method.
Unmarshaling is changed to use a new constructor in order to avoid
changing the signature of the `__init__` method.
I'm unsure how to simplify the test case, as how bravado chooses to create models is unclear to me. Worked towards my use case until was able to replicate a model with a self property.
In reference to issue #125
> [allow-model-self-property]: Allow models to have a "self" property.

- setup.py
Got tired of seeing those py26 builds failing... was a result of the `[format]` extras of the `jsonschema` package containing syntax introduced in 2.7.
The solution was to remove the extras in `install_requires` if installing on version 2.6 and add those extra packages in in manually with the exception of the offending one (`webcolors`).
This isn't the greatest solution but may be a good compromise considering `jsonschema` doesn't even support Python 2.6. We've also lost the ability to validate CSS color codes...
> Fix syntax error in jsonschema dependency with Python 2.6

- bravado_core/formatter.py
- requirements-dev.txt
- setup.py
- tests/formatter/to_wire_test.py
As highlighted on #133 ``date-time`` to-wire function generates invalid result in case of näive datetime objects.
To workaround this issue I'm defaulting the datetime timezone to UTC (in case it is not present).
> date-time formatter to-wire defaults to UTC timezone

- .pre-commit-config.yaml
- .travis.yml
- CHANGELOG.rst
- setup.py
- tox.ini
I'm limiting the ``jsonschema`` dependency in case of Python 2.6 since from [``jsonschema>=2.6.0``](https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst#v260) it is dropped support for Python 2.6. This solution is a temporary fix until we decide to completely drop Python 2.6 support on ``bravado-core``.
In the mean time I have update ``pre-commit`` hooks and dependencies and added travis tests against python 3.5 and 3.6
> Fix Python 2.6 build issue

- CHANGELOG.rst
- bravado_core/param.py
- tests/param/unmarshal_collection_format_test.py
I added a test to check this as well. This fixes an issue where if empty string is an invalid value of the array's format, then it doesn't 400. Not to mention, getting `['']` instead of `[]` is just wrong.
> make unmarshal_collection_format unmarshal empty lists properly

- bravado_core/swagger20_validator.py
- tests/swagger20_validator/enum_validator_test.py
This PR tries to solve Issue #137.
Additionally it fixes a Python2.6 dependency issue  ([jsonschema==2.6.0 drops support Python2.6 support](https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst#v260)) and fixes the cover tox task which was constantly failing. 
The current setup of the enum validation checks that ``instance`` is within the accepted values without caring about ``x-nullable`` field.
Without the ``if`` statement added on ``enum_validator`` the added tests would have the following results:
```
=================================== FAILURES ===================================
test_validate_object_with_different_enum_configurations[value1-enum_values1-False] 
minimal_swagger_spec = <bravado_core.spec.Spec object at 0x10eb1f5f8>
value = {'prop': None}, enum_values = …
```
> Allow nullable enum

- bravado_core/schema.py
- bravado_core/unmarshal.py
- tests/schema/handle_null_value_test.py
- tests/unmarshal/unmarshal_object_test.py
- tests/unmarshal/unmarshal_primitive_test.py
Make sure we consider the default value when unmarshalling. Fixes #153.
> Consider default when unmarshalling

- .travis.yml
As is possible to observe on the last PRs (#155, #152, etc.) we are getting multiple coveralls notification for the same branch.
It happen because ``coveralls`` is executed for all the tox environments.
But actually only one is generating the correct coverage information ``cover``.
To avoid this "spam" in our CR I'm proposing to run ``coveralls`` only if the correct tox environment is executed
> Simplify travis and send coveralls only once

- bravado_core/model.py
- bravado_core/spec.py
- bravado_core/unmarshal.py
- docs/source/config.rst
- tests/conftest.py
- tests/unmarshal/unmarshal_model_test.py
- tests/unmarshal/unmarshal_object_test.py
This CR target Issue #150 (open by @dpopowich).
I have added an additional configuration flag ``nonefy_missing_properties`` which is defaulted to ``True`` for backward compatibility.
Setting the flag to ``False`` [bravado-core](https://github.com/Yelp/bravado-core/blob/master/bravado_core/unmarshal.py#L138-L142) will not set the to all the missing properties to ``None``.
**NOTE**: ``unmarshal_model`` will not be affected by this change since [``model_constructor``](https://github.com/Yelp/bravado-core/blob/master/bravado_core/model.py#L167-L171) will default to ``None`` all the missing properties.
An example is available on https://gist.github.com/macisamuele/b903295f1935ab7270e31145601dd5cb
> Add nonefy_missing_properties configuration

- tox.ini
@macisamuele this fixes the build failure we've been seeing internally. I'm going to make a release once this fix is in.
> Set basepython for pre-commit environment in tox.ini

- CHANGELOG.rst
- bravado_core/model.py
See related Issue #160 for fuller description of underlying issue.
TL;DR - there was an API change that is backward incompatible which is breaking usage of the library. This change re-introduces the old method names with a deprecation warning to allow for a migration grace period.
> Add back old private method names with deprecation warning

- CHANGELOG.rst
- tests/model/create_model_type_test.py
Let's make sure we don't break these methods again until we do a major release.
> Add a test to make sure Model.marshal() and unmarshal() continue to work

- bravado_core/schema.py
- bravado_core/unmarshal.py
- tests/unmarshal/unmarshal_object_test.py
When adding support for default values during unmarshalling in 4.7.0, we didn't handle the case correctly of a property having a null value and no spec. This fixes it. The new test fails without the change and passes with it.
Fixes #163.
> Fix unmarshalling of null values for properties with no spec

- bravado_core/marshal.py
- bravado_core/validate.py
- tests/marshal/marshal_schema_object_test.py
- tests/validate/validate_schema_object_test.py
Support composition when object is passed in request body.
> Fix marshall and validation of allOf

- bravado_core/unmarshal.py
- tests/unmarshal/unmarshal_object_test.py
* Only allow a None to be returned for an optional field if that field is x-nullable.
* Instantiate a missing field to its default value if provided.
> Change how we handle defaults.

- CHANGELOG.rst
- bravado_core/response.py
- tests/response/unmarshal_response_test.py
A JSON response will have "application/json", and only if this is set should
the response content be decoded as such.  Otherwise (until something smarter
comes along), on might as well return the raw response content (which
happens to be the correct thing to do for "text/plain" content).
> Handle responses as JSON only if required to.

- bravado_core/unmarshal.py
We're accidentally reusing the second argument to `format`, not using the third at all. This issue was discovered by the [lgtm static code analyzer](https://lgtm.com/projects/g/Yelp/bravado-core/alerts/).
> Fix error message formatting

- requirements-dev.txt
- test-data/2.0/multi-file-recursive/swagger.json
- test-data/flattened-multi-file-recursive-spec.json
- tests/profiling/conftest.py
- tests/profiling/unmarshal_response_profiler_test.py
- tox.ini
We've noticed bravado response unmarshalling slows down as the number of objects & object complexity increases. Not super surprising, but this at least gives an idea of how each change will effect these benchmarks.
pytest-benchmark has a way to compare benchmarks, but I haven't come up with a decent way to compare a branch's benchmark against some master benchmark. On top of that I'm not sure we're at the point where we should make speed regressions cause failures. 
The output of the benchmarks are available at the end of the pytest suite so people can just look at that.
> Add benchmarking pytests

- Makefile
- bravado_core/schema.py
- tox.ini
Updated is_ref to reduce the number of times is_dict_like gets called. Instance checking is a huge source of slowdown because of the number of times isinstance gets called. Did some comparisons between the benchmarks seen in https://travis-ci.org/Yelp/bravado-core/jobs/264892454 and https://travis-ci.org/Yelp/bravado-core/jobs/264894131
| Py27 - Validated | Old Mean (ms) | New Mean (ms) | Change (% faster) |
|------------------|---------------|---------------|-------------------|
| 1000 small obj   | 201.2373      | 152.8966      | 24.02%            |
| 5000 small obj   | 995.7440      | 783.1190      | 21.35%            |
| 1000 large obj   | 716.8537      | 527.9353      | 26.35%            |
| 5000 large obj   | 3,748.9801    | 2,718.8094    | 27.48%            |
| Py36 - Validated | …
> Updated is_ref to make unmarshal_response ~30% faster

- CHANGELOG.rst
- bravado_core/marshal.py
- tests/marshal/marshal_object_test.py
fixes bug which caused not required None values to be omitted regardless of x-nullable being True
issue #185
> fix: working x-nullable for not required properties

- bravado_core/model.py
- tests/model/model_test.py
Frankly I think models should be more similar to namedtuples in terms of duck-typing. This will help internally as well with our typed model stubs (which are NamedTuples).
> Add _asdict() method to model objects, just like namedtuples have

- bravado_core/formatter.py
- tests/marshal/marshal_schema_object_test.py
This PR makes sure that while formatting/marshaling a primitive type only ``SwaggerMappingError`` could be raised in case of error (as declared by ``marshal_primitive``'s docstring).
Without the code change introduced by this PR ``test_marshal_raises_SwaggerMappingError_if_SwaggerFormat_fails_during_to_wire`` will fail with the following stacktrace
```
F
tests/marshal/marshal_schema_object_test.py:71 (test_marshal_raises_SwaggerMappingError_if_SwaggerFormat_fails_during_to_wire)
minimal_swagger_dict = {'definitions': {'test': {'properties': {'date': {'format': 'date', 'type': 'string'}}, 'required': ['date'], 'type': 'object'}}, 'info': {'title': 'Test', 'version': '1.0'}, 'paths': {}, 'swagger': '2.0'}
def test_marshal_raises_SwaggerMappingError_if_SwaggerFormat_fails_during_to_wire(minim …
```
> Ensure that Marshal raises only SwaggerMappingError

- bravado_core/marshal.py
- tests/marshal/marshal_object_test.py
This bug was introduced by PR #186, I'd like to make a release as soon as possible. I've rewritten the code to check for no spec being available first, which will hopefully remove this source of issues (we've had bugs like this before).
> Fix issue when marshalling a property without a spec and a value of None

- bravado_core/spec_flattening.py
- test-data/2.0/multi-file-specs-with-no-x-model/aux.json
- test-data/2.0/multi-file-specs-with-no-x-model/flattened-multi-file-with-no-xmodel.json
- test-data/2.0/multi-file-specs-with-no-x-model/swagger.json
- tests/conftest.py
- tests/spec/Spec/flattened_spec_test.py
This PR is meant to fix #190.
The main difference introduced in the discovery of the missing models that needs to be injected in the flattened specs.
Basically running ``Spec.from_dict`` will trigger the model discovery and tagging process ([Code](https://github.com/Yelp/bravado-core/blob/v4.8.3/bravado_core/spec.py#L170)) which will modify the injected swagger specs dictionary, and so it will add ``x-model`` into ``known_mappings['definitions']`` objects.
In order to reduce as much as possible the overhead of this operation I'm passing to ``Spec.from_dict`` an object that looks like swagger specs (it won't be valid since ``info`` and ``paths`` are missing) and I'm preventing spec validation.
I know that this could not be 100% clear so I hope that the comments will help 😄
> Ensure model discovery runs for flattened specs

- bravado_core/docstring.py
- bravado_core/model.py
- bravado_core/spec.py
- bravado_core/unmarshal.py
- bravado_core/validate.py
- docs/source/config.rst
- tests/unmarshal/unmarshal_schema_object_test.py
In #183, we made it so that missing types will not be validated. This adds an option to validate missing types as objects.
Question: Do we want to have a third option that causes a hard failure when there is a missing type?
This addresses #192
> added default_type_to_object to default missing types to object

- bravado_core/marshal.py
- tests/marshal/marshal_model_test.py
- tests/model/conftest.py
- tests/model/model_test.py
before converting a model to its dictionary representation, ``marshal_model`` checks that ``model_value`` is an instance of ``model_type``. The check will fail if the model is extracted from a different ``bravado_core.spec.Spec`` instance (even if built from the same Swagger Specs).
This PR updates the check in order to ensure that ``model_value`` has ``_as_dict`` method before running the conversion.
The added tests is failing with the old code and succeeding with the new one.
@sjaensch  could you have a look to this?
> Ensure that models are converted to dictionaries if coming from two bravado_core.spec.Spec instances

- bravado_core/validate.py
- tests/validate/validate_schema_object_test.py
Fixed a small bug would cause swagger validation errors when the obj_type is None.
> Fixed validate_schema_object to handle None types

- bravado_core/marshal.py
- bravado_core/model.py
- tests/marshal/marshal_model_test.py
- tests/model/model_test.py
#194 removed the check around Model class while marshaling a model.
This PR:
* reintroduces the check
* makes sure that a model instance will be recognized as a valid model class even if the model type is originated by a different ``bravado_core.spec.Spec`` object build on top of the same swagger specs.
* deprecates usage of ``_isinstance`` instance method suggesting the use of the *standard* ``isinstance`` python method
> Reintroduce instance check while marshaling models

- bravado_core/param.py
- tests/param/unmarshal_param_test.py
This fixes #198
I'm not 100% sure of the implications of the code path that I changed. I've never directly used the `multi` `collectionFormat`. But the tests pass so...
> fix default array param

- bravado_core/operation.py
- bravado_core/resource.py
- bravado_core/spec.py
- bravado_core/util.py
- requirements-dev.txt
- setup.py
- test-data/2.0/multi-file-recursive/flattened-multi-file-recursive-spec.json
- test-data/2.0/multi-file-recursive/swagger.json
- tests/profiling/conftest.py
- tests/resource/build_resources_test.py
- tests/resource/conftest.py
- tests/spec/Spec/deref_flattened_spec_test.py
- tests/spec/Spec/flattened_spec_test.py
- tests/spec/validate_config_test.py
- tests/util_test.py
- tox.ini
The goal of this PR is to enhance bravado-core performances by using fully dereferenced specs for marshaling and unmarshaling operations.
According to how bravado-core is structured all the decisions made during marsharling and unmarshaling are made on top of ``spec.client_dict`` object which could contain references (``{"$ref": ...}`` objects). In order to make the spec traversing as transparent as possible we take advantage of ``spec.deref`` method which:
- checks if the object is a potential reference object
- eventually dereference the reference
Dereferencing the reference is _expensive_ especially considering that this will be done for all the unmarshaling (no specific caches are used).
A possible solution is to completely dereference the spec at build time, doing so ``deref`` method …
> Fully dereference specs for performance improvements

- test-data/2.0/security/swagger.json
- tests/operation/security_object_test.py
- tests/security_test.py
- tests/validate/validate_security_object_test.py
The goal of this PR is to fix [travis tests failure](https://travis-ci.org/Yelp/bravado-core/jobs/291577938#L416).
While fixing the ``flake8`` failure I noticed that ``test_only_one_security_definition_in_use_at_time`` needed to be refactored a bit and that was not actually testing the different cases of exceptions.
> Improve security definitions tests

- bravado_core/schema.py
isinstance(something, Mapping) is very slow in Python (see https://stackoverflow.com/questions/42378726/why-is-checking-isinstancesomething-mapping-so-slow) and most of the time is_dict_like in schema.py is called with an actual dict instance instead of some other type of mapping.
This change optimizes for that common use-case by doing a cheap dict is_instance check and by only executing the more expensive check if it's not a dictionary. This yields an approx 25% performance improvement for some of my test cases that use very large (around 400 kb) JSON responses.
> Optimize is_dict_like performance when called with a dict instance

- bravado_core/spec.py
- bravado_core/swagger20_validator.py
- test-data/2.0/polymorphic_specs/swagger.json
- tests/model/model_test.py
Fixes #210 
The issue reported is caused by two concurrent factors:
1. in case of fully dereferenced specs polymorphic checks are performed on specs that have references (but ``deref`` will not resolve them) -> ensure that Spec is built using fully dereferenced specs
2. in case of fully dereferenced specs (since the specs are obtained after spec flattening) we should not use ``spec.client_dict``, but using ``spec._internal_client_dict`` will not give us any guarantee to get the required definition. -> use spec.definitions instead
I've added ``test_ensure_polymorphic_objects_are_correctly_build_in_case_of_fully_dereferenced_specs`` to ensure that we're correctly covering this case.
@gstarnberger : FYI
> Ensure proper polymorphic objects handling in case of fully dereferenced specs

- bravado_core/spec.py
- tests/spec/Spec/deref_flattened_spec_test.py
- tests/spec/validate_config_test.py
- tests/validate/validate_object_test.py
Fixes #217 .
The goal of this PR is to fix the current [``Yelp/bravado``](https://github.com/Yelp/bravado) [build failure](https://travis-ci.org/Yelp/bravado/builds/297225901).
``bravado`` is failing because it used to inject ``also_return_response`` configuration into ``bravado-core`` configs, which is not using that config.
Since ``bravado-core`` is not using this config, I'm not adding it into ``CONFIG_DEFAULTS``, but removing the logic that strips out extraneous configurations.
This PR exposes also ``_deref`` method in order to force dereferencing of objects even if ``internaly_dereference_ref`` in order to reduce ``test_deref_flattened_spec_not_recursive_specs`` flakyness.
> Don't remove extraneous configurations, only warn about their presence

- tests/spec/Spec/deref_flattened_spec_test.py
> xfail test_deref_flattened_spec_not_recursive_specs test

- bravado_core/content_type.py
- bravado_core/response.py
- setup.py
- tests/response/IncomingResponse_test.py
- tests/response/unmarshal_response_test.py
- tests/response/validate_response_body_test.py
(1) `make test` with added unit tests
(2) Manually tested the client side by calling a mocked endpoint that responds with a application/msgpack content type and data, and verified the final response from Bravado was properly deserialized
(3) Manually tested the server side response validation by requesting an endpoint which responds with a application/msgpack content type that uses pyramid_swagger
https://github.com/striglia/pyramid_swagger/pull/223
https://github.com/Yelp/bravado/pull/324
> Fixes #214 - Added msgpack support

- bravado_core/spec.py
- tests/spec/Spec/build_test.py
- tests/spec/Spec/deref_flattened_spec_test.py
This pull request includes two optimizations
This log.debug causes 8000+ lines to be logged during my experiment as `deref` can be called thousands of times for one API call. With this removed, less than 10 lines were logged, so this probably should be removed.
Also, removing this causes a performance gain of almost 9%*
Instead of checking if internally_dereference_refs is set every time in deref, it might be more efficient to just patch it.
This leads to a performance gain of 3.2%*
*In my custom benchmark tests with an very large spec with many refs
```
------------------------------------------------------------------------------------------ benchmark 'test_large_objects': 12 tests -----------------------------------------------------------------------------------------
Name (time in …
```
> Performance Improvements

- bravado_core/marshal.py
- bravado_core/schema.py
- bravado_core/unmarshal.py
A comment made internally by @gstarnberger made me look into why we're calling ``collapsed_properties`` so often. It turns out we call ``get_spec_for_prop`` for every property of an object, both when marshalling and unmarshalling. That method fetches the collapsed properties of the parent object - every time! This PR changes marshalling and unmarshalling to compute the properties once and then pass them into ``get_spec_for_prop`` (and saves one more additional call to it when unmarshalling).
These are the timing reductions I observed locally when running our benchmark suite:
| Name | Mean time reduction |
| -- | -- |
| large_objects[not_validate-full-deref-100]  | 21.62% | 
| large_objects[not_validate-with-refs-100]   | 19.90% | 
| large_objects[validate-full-deref-100]      | 8.99% | 
| …
> Make sure we don't unnecessarily call collapsed_properties

- CHANGELOG.rst
- bravado_core/response.py
- setup.py
- tests/response/unmarshal_response_test.py
- tests/response/validate_response_body_test.py
Fixes #227 
- Updated unit tests and ran `make test`
- Tested server side response by using an API endpoint that renders `application/msgpack` responses and checked that the server side Swagger response validation worked properly
- Tested client side by using a `bravado` client which used a version of `bravado-core` with these changes to request an API endpoint that renders only `application/msgpack`. First, check that requesting without the `Accept: application/msgpack` results in a 500 response status. Then, check that requesting with the `Accept: application/msgpack` results in the desired response.
> Fixes #227 - Use msgpack-python instead of umsgpack

- bravado_core/marshal.py
- tests/marshal/marshal_model_test.py
Fixes: #222 
The goal of this PR is to remove model type check while marshaling models.
The "old" behavior adds a sort of type validation even if ``validate_response`` is set to false.
With this PR the only check that is made is that ``marshal_model`` is a ``bravado_core.model.Model`` instance, so we have guarantees that ``model_value._as_dict()`` will not raise an error.
> Remove instance type check while marshaling models

- bravado_core/param.py
- tests/param/marshal_param_test.py
This is an updated version of #237. Long story short: bravado is handling quoting of query and formData params correctly, #237 would have broken that. On the other hand, we do not properly handle path params that need quoting. I'm assuming this hasn't surfaced earlier because people typically only have numeric IDs or ASCII strings as values for params that are passed in the URL.
I have integration tests for bravado and bravado-asyncio that show that query argument escaping works, I'll publish PRs once this change is merged in (I need this fix so that the integration tests for it that I wrote don't fail).
> Properly quote path params

- bravado_core/spec.py
- tests/formatter/to_python_test.py
- tests/formatter/to_wire_test.py
- tox.ini
Also, let's make sure pre-commit uses Python 2.7.
> Use yaml.safe_load, remove Python 3 specific test code

- bravado_core/model.py
I had a case where I was using `additionalProperties: true` (actually that's the default I think) and I noticed that the repr() on the response did not include them in the object.  It includes them in the dict when `use_models: false` or _as_dict() is called.
Should it include them in the repr(Model) ?
> Change model repr() to return additionalProperties

- bravado_core/param.py
- bravado_core/spec.py
- docs/source/formats.rst
- tests/formatter/to_python_test.py
- tests/formatter/to_wire_test.py
This PR is to fix the need for overriding DEFAULT_FORMATS
I welcome feedback, particularly on the example provided in docs as I am not 100% clear on the validate function in particular, I haven't quite figured out when this is called.
Closes #235
> Fix 235 allow override formats

- bravado_core/operation.py
- bravado_core/resource.py
- bravado_core/util.py
- tests/operation/build_params_test.py
- tests/resource/build_resources_test.py
- tests/util_test.py
- tox.ini
Currently, bravado-core only makes sure the operationId is a valid Python identifier. Let's do the same for resources and params. My primary concern was backwards compatibility; I've ran bravado tests with this bravado-core branch and they all passed, including a few new integration tests that test the new behavior. I've used this branch with the bravado-asyncio test suite as well, all tests pass.
The second concern was discoverability. The names shown when using dir(client) or dir(resource) in bravado need to be the sanitized names. That's why the real name is only added as an alias.
Closes #200, #215.
> Sanitize param and resource names

- bravado_core/request.py
- test-data/2.0/petstore/swagger.json
- tests/operation/security_object_test.py
- tests/request/unmarshal_request_test.py
Unfortunately, unmarshal_request uses the dict key of op.params as key in the request_data. This is incorrect with the changes made to sanitize param names. It should always use the real param name.
> Make sure we use the real param name when unmarshalling

- bravado_core/spec_flattening.py
- bravado_core/util.py
- setup.py
- tests/util_test.py
This CR exposes ``determine_object_type`` capability in a backward compatible way.
I'm exposing this functionality because I'm trying to extend how bravado-core detects models and I need to know the type of "object" I'm working on.
Respect the original code I'm using ``enum`` to represent the state instead of integers in order to have a cleaner interface.
> Expose determine_object_type method

- bravado_core/model.py
- docs/source/models.rst
- tests/model/collect_models_test.py
- tests/spec/Spec/build_test.py
Current model discovery generates models also for _not models_ object specs.
This PR aims to solve this issue.
Assuming that the following is a snippet of the swagger specs
```json
{
"definitions": {
"list": {
"type": "array",
"items": {"type": "string"},
"x-model": "list"
}
}
...
}
```
Before this PR this generates a ``list`` model (``assert Swagger.from_url(...).definitions == {'list': mock.ANY}``)
After this PR ``assert Swagger.from_url(...).definitions == {}``
> Collect models will not create models for not models objects

- bravado_core/spec.py
- tests/model/model_test.py
- tests/profiling/unmarshal_response_profiler_test.py
- tests/spec/Spec/build_test.py
In order to optimize dereferencing process, we're dynamically defining ``deref`` method according to ``internally_dereference_refs`` value.
This implies that during spec post-processing the no-op deref will be used if ``internally_dereference_refs`` is enabled.
This CR fixes this issue by:
* forcing ``deref`` to be an alias of ``_force_deref``
* overriding ``deref`` (to be a _no-op_) only after spec post-processing (model discovery) runs over the specs
An additional change provided by this CR is related to how models are saved in case of ``internally_dereference_refs``.
Before this change, we were running ``descend`` (on ``post_process_spec``) twice to guarantee that the models get's overridden; but I noticed that this was not happening for models that are not directly referenced (ie. …
> deref is overridden after building Spec

- tests/conftest.py
- tests/operation/conftest.py
- tests/operation/security_object_test.py
- tests/param/unmarshal_param_test.py
- tests/resource/conftest.py
This PR removes not used fixtures and makes sure that all the tests get executed.
I've noticed this while checking coverage of the test related code.
ℹ️ : I've moved ``test_security_object_and_definition_constants`` to ensure its execution (it was in conftest and seemed that pytest was not running the test)
> Small tests refactory to ensure high testing coverage

- bravado_core/model.py
- bravado_core/response.py
- bravado_core/spec.py
- bravado_core/swagger20_validator.py
- tests/model/bless_models_test.py
- tests/model/collect_models_test.py
- tests/model/get_model_name_test.py
- tests/model/tag_models_test.py
- tests/spec/Spec/build_test.py
- tests/spec/Spec/deref_flattened_spec_test.py
- tests/spec/from_dict_test.py
This CR improves the model name determination strategy used during model discovery.
The original approach was:
* use ``key`` for models in ``definition``
* use ``x-model`` for models around the specs
The goal of this PR tries to unify this in a common approach.
The model name is determined as:
1. use ``x-model``
2. use ``title``
3. if the model is in ``#/definitions`` use the ``key``
WARNING: this does CR not try to improve detection of duplicated models, but it should simplify future work on that direction
> Improve model name determination by using title information

- CHANGELOG.rst
- bravado_core/model.py
- tests/model/tag_models_test.py
The current implementation of ``bravado-core`` raises ``ValueError`` exception if ``tag_models`` or ``bless_models`` identifies a duplicated model.
This behavior is correct is ``use_models`` config is set to ``True``, but it is erroneous if no models are required to the ``Spec`` object.
This PR tries to solve this issue.
> Duplicate models should not raise if not use models

- bravado_core/spec.py
This PR is a minor cleanup of ``descend`` input parameters.
> Remove not used visited_refs from post_process_spec descending flow

- CHANGELOG.rst
- bravado_core/__init__.py
- bravado_core/param.py
- tests/param/cast_request_param_test.py
In #258, it was discovered that multiple query parameters of a primitive type cause a `TypeError` causing an application server to 500 instead of 400. This change catches the `TypeError`, allowing JSON Schema to handle the exception and return a 400 instead.
> If type casting fails on a ``TypeError`` allow JSON Schema to handle the error

- bravado_core/spec.py
- tests/spec/build_api_serving_url_test.py
Currently, if you have a swagger spec with multiple supported schemes, and the origin url has a different scheme, then you will get a `SwaggerSchemaError`. If you have only _one_ supported scheme, however the origin url has a different scheme, then the scheme will simply be the supported scheme.
I think this is an arbitrary distinction, and we should prefer to either 1) fail in both cases or 2) succeed in both cases.
I much prefer option 2, which is what this PR does.
To repro on master:
1. Create swagger spec with schemes `http` and `https`
2. Call `from_dict` with `origin_url=file://foo/swagger.json`
Other (separate) observation: `build_api_serving_url` takes a `preferred_scheme` option, but this is actually used nowhere. Do we still need it? If so, should we expose this as part of the …
> fixes multi-scheme override logic

- bravado_core/param.py
- tests/param/add_file_test.py
Add support for specifying the 'filename' parameter in 'Content-Disposition'
header when making multipart/form-data POST requests.
The filename is specified by using a tuple of this form:
client.foo.post_bar(fooFile=("my-filename", "file content"))
The call above will generate approx this request:
Host: localhost:9090
User-Agent: python-requests/2.18.4
Content-Length: XXX
Content-Type: multipart/form-data; boundary=15ebe1de468e4b759e100591280b9144
--15ebe1de468e4b759e100591280b9144
Content-Disposition: form-data; name="fooFile"; filename="my-filename"
file content
--15ebe1de468e4b759e100591280b9144--
(This is the same patch as in https://github.com/Yelp/bravado-core/pull/224, but now with a unit test on the new code)
> allow to specify Content-Disposition filename

- tests/spec/Spec/build_test.py
Running tests produces the following warning message
```
tests/spec/Spec/build_test.py::test_build_with_internally_dereference_refs[True]
/Users/maci/pg/github/bravado-core/bravado_core/spec_flattening.py:176: Warning: It is recommended to set origin_url to your spec before flattering it. Doing so internal paths will be hidden, reducing the amount of exposed information.
category=Warning,
-- Docs: http://doc.pytest.org/en/latest/warnings.html
```
The goal of this PR is to remove this warning and keeping clean output of the results
> Remove warning from tests execution

- .gitignore
- bravado_core/spec.py
- bravado_core/spec_flattening.py
- bravado_core/util.py
- test-data/2.0/multi-file-multi-directory-spec/definitions.yaml
- test-data/2.0/multi-file-multi-directory-spec/endpoint/parameters.yaml
- test-data/2.0/multi-file-multi-directory-spec/endpoint/v1/objects.yaml
- test-data/2.0/multi-file-multi-directory-spec/endpoint/v1/paths.yaml
- test-data/2.0/multi-file-multi-directory-spec/endpoint/v1/responses.yaml
- test-data/2.0/multi-file-multi-directory-spec/flattened-multi-file-multi-directory-spec.json
- test-data/2.0/multi-file-multi-directory-spec/swagger.yaml
- test-data/2.0/multi-file-specs-with-no-x-model/flattened-multi-file-with-no-xmodel.json
- tests/spec/Spec/deref_flattened_spec_test.py
- tests/spec/Spec/flattened_spec_test.py
- tests/spec/from_dict_test.py
- tests/util_test.py
While working on internal specs I've spotted two issues related to flattening and dereferencing specs with relative links on different directories.
Everything works fine if the references are not on different files, but as soon as we reference a file on a different directory all the links on the new files are relative to the new path.
The issue is caused because:
* reference resolving does not take in consideration the resolution scope (changes on `bravado_core/spec_flattening.py`)
* flattening specs requires resources to be available; as resources are not built at the time of `flattened_spec` call, enforcing resource building as an extra step of `run_post_processing` fixes the issue
**Note**:
while doing those changes I've also noted that `_internal_spec_dict` was returning …
> Fix spec flattening in case of relative references

- tests/spec/Spec/deref_flattened_spec_test.py
During PR #263 I've de-xfailed `test_deref_flattened_spec_not_recursive_specs` as it looked to be pretty stable.
Apparently this is not true, as it failed on travis (and succeed after pressing of rebuild) and fails on internal jenkins machines.
I'm xfailing it back
> re-xfail test_deref_flattened_spec_not_recursive_specs

- bravado_core/param.py
- tests/param/marshal_param_test.py
- tests/param/unmarshal_param_test.py
While working on https://github.com/striglia/pyramid_swagger/pull/231 I've noticed that bravado-core, during the parameter marshaling and unmarshaling process, checks if the parameter is required in case `raw_value is None`.
Unfortunately the check does not use `param.required` attribute but `schema.is_required` method.
In case the parameter type is not an object the two approaches are equivalent as
* `schema.is_required(swagger_spec, param_spec)` safely gets `required` attribute from `param_spec`
* `param_spec` (retrieved from `get_param_type_spec` returns param.spec
In case of body parameter `param_spec` contains the `schema` attribute of the parameter, so `schema.is_required` extracts the required properties of the schema rather than required attribute of the parameter.
This PR …
> Fix is parameter required check in marshal_param and unmarshal_param

- bravado_core/model.py
- bravado_core/spec_flattening.py
- test-data/2.0/multi-file-multi-directory-spec/flattened-multi-file-multi-directory-spec.json
- test-data/2.0/multi-file-specs-with-no-x-model/flattened-multi-file-with-no-xmodel.json
- tests/model/bless_models_test.py
- tests/model/collect_models_test.py
- tests/model/model_discovery_test.py
- tests/model/post_process_spec_test.py
- tests/model/tag_models_test.py
- tests/spec/Spec/build_test.py
The goal of this PR is to replace `path` with `json_reference` during model discovery.
The change allows to:
* simplify the identification of models that are under `[any-file]#/definitions`
NOTE: an additional PR will be provided to get models from all linked files (as affirmed in documentation)
* improve exceptions in case of duplicated models as they will not contain the paths in swagger specs but the _real_ references on files (extremely useful in case of multi file spec)
> Use json references instead of swagger path

- bravado_core/model.py
- test-data/2.0/multi-file-recursive/aux.json
- test-data/2.0/multi-file-recursive/aux_2.json
- test-data/2.0/multi-file-recursive/flattened-multi-file-recursive-spec.json
- test-data/2.0/multi-file-recursive/swagger.json
- test-data/2.0/multi-file-specs-with-no-x-model/flattened-multi-file-with-no-xmodel.json
- tests/model/collect_models_test.py
The goal of this PR is to make bravado-core compliant with its own documentation :)
[Model discovery point 2](http://bravado-core.readthedocs.io/en/latest/models.html#model-discovery) states
> Search for refs that refer to external definitions with pattern `<filename>#/definitions/<model name>`
The current implementation was not fully scanning all the referenced files.
This PR achieves the goal of scanning over all the referred files during model discovery process by keeping track of the already fully scanned files.
**Potential issues**
I might be too pessimistic / paranoid but I prefer to make it "public" as early as possible
As we'll start to fully scan (and follow possible references) the referenced files we could end up in some endless process.
A possible example of the mentioned …
> Get models from definitions of referred files

- bravado_core/spec.py
- tests/spec/validate_config_test.py
Particularly, we'd like to introduce a few more configs to bravado, and reusing the bravado-core config store seems like a sensible idea.
> Allow extra configs so tools built on top of bravado-core can use them

- bravado_core/docstring.py
- bravado_core/exception.py
- bravado_core/model.py
- bravado_core/operation.py
- bravado_core/param.py
- bravado_core/response.py
- bravado_core/schema.py
- bravado_core/security_requirement.py
- bravado_core/spec.py
- bravado_core/spec_flattening.py
- bravado_core/swagger20_validator.py
- bravado_core/unmarshal.py
- bravado_core/validate.py
- tests/param/cast_request_param_test.py
This PR proposes some cleanup of the codebase:
* done typos finding and removal
* removed outer scope variable shadows
> Remove/reduce typos and remove build-in variable shadows

- bravado_core/spec_flattening.py
- test-data/2.0/multi-file-multi-directory-spec/flattened-multi-file-multi-directory-spec.json
- test-data/2.0/multi-file-recursive/flattened-multi-file-recursive-spec.json
- test-data/2.0/multi-file-specs-with-no-x-model/flattened-multi-file-with-no-xmodel.json
- tests/spec/Spec/flattened_spec_test.py
The idea of this PR is to post-process the flattened specs in order to rename `#/definitions/<schema-object>` to `#/definitions/<model-name>` if possible.
Doing this is moistly useful to enhance human readability of the provided specs.
The post-processing process takes into account that it could be possible that `#/definitions/<model-name>` is for some reason already in use, if it is the case it won't rename references and objects guaranteeing that specs will be equivalent
> Add logic to rename definitions keys to model names, if possible

- bravado_core/spec_flattening.py
- test-data/2.0/multi-file-multi-directory-spec/flattened-multi-file-multi-directory-spec.json
- test-data/2.0/multi-file-recursive/aux_2.json
- test-data/2.0/multi-file-recursive/flattened-multi-file-recursive-spec.json
While refactoring the flattening process I've noticed that in case of inline models (with `x-model` defined) the flattening replicates the model definition twice: inline the original object and in `#/definitions/`
This PR does essentially some clean-up :)
> Replace inline models with top-level definitions

- .coveragerc
- bravado_core/param.py
- tests/param/marshal_param_test.py
The goal of this PR is to fix #281 
The approach used is really similar to the one already used for `unmarshal_param`.
I've defined a function that stringifies the paramater if its location is `header` or `query`
> Generalize parameter encoding (as done for parameter string decoding)

- bravado_core/param.py
- tests/param/marshal_param_test.py
array params are either already stringified or left as untouched if collectionFormat is multi. The latter case breaks with bravado-core 5.0.5 due to the behavior of the new `encode_request_param` function. An integration test failure in bravado-asyncio surfaced the issue. This PR fixes it.
> Fix marshalling of array params with collectionFormat multi

- tox.ini
It's unclear why it's failing on travis, it passes locally.
> Make docs is failing on travis with Sphinx 1.8.0, use a lower version

- bravado_core/operation.py
- test-data/2.0/security/swagger.json
- tests/validate/validate_security_object_test.py
While working on some internal investigation I've noticed that a bug was present into the implementation of `validate_security_object` method.
The bright side of it is that I could be triggered with a very specific case which, considering that no issues were open, is uncommon.
To trigger the issue we should have multiple matched security requirements with at least one unmatched security requirement, check `test-data/2.0/security/swagger.json` for an example.
The validation logic of the security component is defined in [`validate.validate_security_object`](https://github.com/Yelp/bravado-core/blob/v5.0.6/bravado_core/validate.py#L108), if we would extract from it the main actions are
1. ...
2. keep track of the index of all the matching security definitions (note: the used order is the …
> Fix issue with multiple security definitions ordering

- bravado_core/swagger20_validator.py
- tests/validate/validate_object_test.py
While performing validation of polymorphic objects the logic is split into 2 main areas:
* validate the object according to the "common" object definition
* identify the schema of the discriminated model and validate the object against that schema
In order to overcome unbounded-recursion (related to jsonschema validation) the `discriminator_validator` was implementing a _removal_ logic to ensure that the "common" object definition is removed from the schema (as it was already validated).
In order to prevent tampering of the model spec saved in the Spec object we were doing a `deepcopy` of the model spec.
If `internally_dereference_refs` is not enabled the `schemas_to_remove` is correctly evaluated as the dictionaries do not have a recursive structure and so `__eq__` is able to properly …
> Fix unbounded recursion in polymorphic object validation

- bravado_core/response.py
- setup.py
- tests/model/create_model_type_test.py
- tests/model/model_test.py
While running some local tests I noticed that a set of warnings are thrown, among them one was pretty new and was related to a deprecation into `msgpack-python` library.
The goal of the PR is to:
* address msgpack-python deprecation by setting the min required version and removing usage of `encoding` in favour of `raw`
* silence bravado-core deprecation warnings that are thrown in purpose
> Remove usage of deprecated msgpack parameter

- bravado_core/spec.py
- tests/spec/build_api_serving_url_test.py
According to the Swagger spec we should not use the path part of the
spec URL, but instead just use the host part of the URL (see the
existing comment for build_api_serving_url, as well as
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields
).
Also update tests to match new behaviour.
I don't know if bravado users depend on the current behavior - feedback appreciated.
> Don't use Swagger spec path for API URL

- bravado_core/swagger20_validator.py
- tests/validate/validate_object_test.py
Fixes #301 
The current implementation of `bravado_core.swagger20_validator.discriminator_validator` assumes that `discriminator_attribute` is present in `instance`.
This assumption is valid if we are able to guarantee that `required` validator operates before `discriminator` validator.
As we shoudln't making assumptions on keywords validation order we should make sure that the validator is more resilient to this type of issue, we should be removing the assumption.
According to the swagger specs, the discriminator field has to be a required field of the object, so to keep users less "distracted" I'm returning an error message like the one returned by the jsonschema library that highlights the fact that the attribute is missing.
> Fix discriminator validation

- .pre-commit-config.yaml
- .secrets.baseline
- CHANGELOG.rst
- bravado_core/swagger20_validator.py
- docs/source/index.rst
- tests/param/marshal_param_test.py
- tests/swagger20_validator/enum_validator_test.py
- tests/swagger20_validator/format_validator_test.py
- tests/swagger20_validator/required_validator_test.py
- tests/swagger20_validator/type_validator_test.py
Fixes: #303 
The goal of this PR is to guarantee bravado-core interoperability with jsonschema version 3 (released only in alpha for now).
The new release is changing how the validator methods are named within jsonschema._validators package.
In general we should not _import_ private definitions, but this was done.
In order to make bravado-core able to work with the current jsonschema releases and the new release (alpha released) we need to call the _original_ validators using a different approach.
Instead of calling validator methods from the private module we could extract them from `Draft4Validator.VALIDATORS` class attribute (by using only public informations).
> Remove direct usage of jsonschema._validators

- bravado_core/spec.py
- tests/conftest.py
- tests/spec/Spec/build_test.py
- tests/spec/build_api_serving_url_test.py
This new option addresses issues arising from 'basePath' not being
present in a given spec.
According to the 2.0 spec, "If it is not included, the API is served directly
under the host. The value MUST start with a leading slash (/).".
10836363 made the SwaggerClient compliant with the spec (basePath is now
implicitly set to '/' if field is missing from spec). However, this broke
existing code that utilizes the SwaggerClient (see Issue #299).
The current (spec-compliant) behaviour remains with this new option as
it defaults to False. Overriding this default with 'True' means the path
element of the URL used to retrieve the spec will be used instead.
> Add new 'use_spec_url_for_base_path' boolean config option

- docs/source/config.rst
read the docs documentation is missing two Spec configuration flags `internally_dereference_refs` and `use_spec_url_for_base_path`.
The goal of this PR is to add them 😄
> Add internally_dereference_refs and use_spec_url_for_base_path Spec config in docs

- bravado_core/schema.py
- test-data/2.0/specs-with-None-in-ref/flattened.json
- test-data/2.0/specs-with-None-in-ref/swagger.json
- tests/conftest.py
- tests/spec/Spec/flattened_spec_test.py
The goal of this PR is to make sure that reference detection takes care of the actual value of the json-pointer (value of `$ref` attribute).
This issue was noticed while debugging a recursion error that was happening while flattening specs that have `None` value in references.
While this condition is odd while writing with JSON specs it is not uncommon while working with YAML specs (we're humans and is not so weird to forget to quote a reference if it starts with `#`).
```yaml
definitions:
mod1:
type: object
mod2:
$ref: #/definitions/mod1   <- this will be rendered as {'$ref': None} as `#` in YAML represents a comment
```
Unbounded recursion during flattening is happening because `deref` will try to dereference it and it will actually succeed by getting the original object (the whole …
> Be resilient in case of None in references

- tests/validate/validate_object_test.py
We uncovered an issue with a test on Python 2.7 internally, which fails due to the error message being `u'birth_date' is a required property'` (with the leading `u` character), while the assertion didn't expect the `u` to be there.
Further debugging showed that this is not failing on travis due to us using simplejson, and its C module `_speedups.so` specifically. Using that we get `str` objects when loading JSON, while not using it (or using the stdlib `json` module) yields `unicode` strings and dictionary keys.
The Python 2 documentation for the `json` module [clearly states](https://docs.python.org/2/library/json.html) that JSON strings should be decoded into Python unicode strings. So the simplejson C module changes behavior here.
It turns out we don't need that assertion anyway, so …
> Remove unneded assertion

- .pre-commit-config.yaml
- Makefile
- bravado_core/schema.py
- bravado_core/spec.py
- tox.ini
Starting with Python 3.8 it's not possible to import `Mapping` from `collections`, we'll need to use `collections.abc` as package.
Additionally, I'm introducing the separate flake8 pre-commit hook as well as changing things around pre-commit hook installation slightly to make sure running `tox` directly also installs them. I've also incorporated the fix from #319 with one slight modification so the tests pass on Python 3.
> Fix Python 3.8 issue, use separate flake8 pre-commit hook, fix tests

- bravado_core/param.py
- tests/request/unmarshal_request_test.py
Fixes: #321 
The following PR addresses the not needed assumption of body presence in case a body parameter is defined.
In case of an operation defined like
```yaml
paths:
/endpoint:
post:
parameters:
- in: body
name: body
required: false
schema:
type: object
```
a call like `curl -X POST .../endpoint` would fail with a stacktrace like
```
Traceback (most recent call last):
File "/Users/maci/my_service/virtualenv_run/lib/python3.6/site-packages/bravado_core/param.py", line 183, in unmarshal_param
raw_value = request.json()
File "/Users/maci/my_service/virtualenv_run/lib/python3.6/site-packages/pyramid_swagger/tween.py", line 271, in json
return getattr(self.request, 'json_body', {})
File "/Users/maci/my_service/virtualenv_run/lib/python3.6/site-packages/pyramid/request.py", line 237, in …
```
> Do not assume that request body is present in case of optional body parameter

- bravado_core/spec.py
This PR is a re-proposal of #98 
The objective is to allow users of bravado_core.spec.Spec to easily override the reference handlers, allowing to extend the set of supported protocols, formats, etc.
I wanted to re-use the original PR, but due to merge conflicts and absence of the remote fork I had to apply the patch on a new branch.
@Arkq: FYI
> build_http_handlers as Spec instance method (allow subclassing)

- bravado_core/model.py
- tests/model/model_test.py
It was reported internally that deepcopy doesn't work on model instances and fails with an infinite recursion exception. The test I'm adding failed without my change.
In doing a deep copy we should only copy the model properties, not the metadata set on the class. All of them are stored in the `__dict` attribute.
> Implement deepcopy support for Model instances

- CHANGELOG.rst
- bravado_core/schema.py
I'm working a Python 3.7 project internally and I get `DeprecationWarning`s in Python 3.7 to switch to `collections.abc`. This change changes the default to collections.abc so that we stop getting the warning messages.
This should safe for all Python versions, since if a Python version doesn't have `collections.abc`, we'll fallback to `collections`.
> Default to importing collections.abc instead of collections

- bravado_core/util.py
- tests/util_test.py
The goal of this CR is to allow usage of `cached_property` as lazy evaluated and cached class attribute in case of usage in meta class.
The idea of this change is to allow definition of `Model` class attributes as lazy attribute, this could improve creation speed (not all the attributes need to be defined at init time) as well as memory consumption (only needed attributes will be evaluated).
> Use setattr instead on manipulating __dict__ in cached_property

- Makefile
- bravado_core/model.py
- bravado_core/util.py
- tests/util_test.py
The goal of this PR is to use lazy evaluated and cached attributes on the model class.
By doing so we can avoid to pre-evaluate, for all the models, certain features like `_properties` or `_inherits_from` which could be time consuming.
Thanks to the usage of `@lazy_class_attribute` we do evaluate the property only once per model type and reuse the evaluation result for the following calls.
An other change done by this PR is to use `slots` in the `Model`, thanks to this we can reduce the memory footprint of the model instances without negatively impacting the performances.
NOTE: PR #329 objective was only to extend `@cached_property` to be used in meta classes, the extension has not be used here because we would have had to override `__getattribute__` as well causing a performance hit of …
> Use lazy attributes on model

- bravado_core/_compat.py
- bravado_core/unmarshal.py
- bravado_core/util.py
- bravado_core/validate.py
- setup.py
- tests/conftest.py
- tests/model/model_test.py
- tests/response/unmarshal_response_test.py
- tests/schema/collapsed_properties_test.py
- tests/spec/Spec/deref_flattened_spec_test.py
- tests/spec/from_dict_test.py
- tests/unmarshal/unmarshal_array_test.py
- tests/unmarshal/unmarshal_model_test.py
- tests/unmarshal/unmarshal_object_test.py
- tests/unmarshal/unmarshal_primitive_test.py
- tests/util_test.py
The goal of the PR is to fix issues spotted while working on #331.
Namely I noticed that:
* unmarshaling is not unmarshaling additional properties.
Unmarshaling `{"key1": "2019-05-22"}` against the following schema
`{"type": "object", "additionalProperties": {"type": "string", "format": "date"}}`
would result into `{'key1': '2019-05-22'}` (master) instead of `{'key1': datetime.date(2019, 5, 22)}` (after this PR)
* when default values are used they are not unmarshaled.
Unmarshaling `{}` against the following schema
`{"type": "object", "property": {"key1": {"type": "string", "format": "date", "default": "2019-05-22"}}}`
would result into `{'key1': '2019-05-22'}` (master) instead of `{'key1': datetime.date(2019, 5, 22)}` (after this PR)
* ~unmarshaling a polymorphic object into a dictionary …
> Enhance unmarshaling of additional properties and defaults

- tests/conftest.py
- tests/model/conftest.py
- tests/unmarshal/unmarshal_object_test.py
- tests/unmarshal/unmarshal_schema_object_test.py
This PR is meant to update some tests in order to allow the removal of test changes in #331 .
The idea to remove test related changes in #331 is mostly lead by the fact that modifying tests there might reduce the confidence that such changes are valid and not changing the library behaviour.
> Update tests pre unmarshaling performance enhancements

- bravado_core/_compat.py
- bravado_core/spec.py
- bravado_core/unmarshal.py
- bravado_core/util.py
- bravado_core/validate.py
- tests/util_test.py
This PR aims to improve the performances of `memoize_by_id` decorator while preserving the external signature.
By profiling the code I've noticed that a lot of time is spent into the generation of the cache key of `@memoize_by_id` decorator (specifically on the execution of`inspect.getcallargs(func, *args, **kwargs)`.
This PR adds a small optimisation on the `make_key` functionality if the function is invoked with kwargs only parameters.
In such condition we don't need to use `getcallargs` to determine the mappings between parameter names and associated values.
In order to preserve the fact that `getcallargs` resolves default attributes as well the added code does manually deal with them (it's a bit ugly but by doing so we can get additional performance improvements).
Data
----
Raw data …
> Improve memoize by id if used with kwargs only

- bravado_core/unmarshal.py
Double checking the performance improvements of #336, I've noticed that the final version (the one that has been merged) does have equivalent performances of the "original" code.
Comparing performance results between the individual commits I've found a specific commit responsible for the majority of the performance issues:  https://github.com/Yelp/bravado-core/commit/bfa6ceec0cf817a397841602a1a4b4281e8fd77e
In order to restore performances, this PR is going to re-introduce the usage of partials.
The drawback of partials is that we might not have accurate type checking on the arguments of the function, but it provides way better performances that a _normal_ function call.
Raw data on https://gist.github.com/macisamuele/785ae30d49ab94244734fb5697930893
The changes, introduced during the …
> Use partials as they do not introduce the overhead of wrapping functions

- bravado_core/unmarshal.py
- tests/unmarshal/unmarshal_primitive_test.py
Changes in the unmarshaling logic (PR #336) revealed a new bug being introduced while working with primitive types, which uses a format that is unknown to bravado-core.
This was observed while trying to integrate the library into an internal service.
The goal of this PR is to address the issue and to create a dedicated test that would help to catch this type of error in the future.
If you run the test on the original codebase (current Yelp/master) the test would fail, but running it with the changes in bravado_core/unmarshal.py proposed by this PR the test would be green.
NOTE: This approach is already used in the marshaling flow (PR #339)
> Ensure that unmarshal uses the format only if defined

- bravado_core/_compat_typing.py
- bravado_core/_decorators.py
- bravado_core/marshal.py
- bravado_core/model.py
- bravado_core/unmarshal.py
- mypy.ini
- tests/marshal/marshal_array_test.py
- tests/marshal/marshal_model_test.py
- tests/marshal/marshal_object_test.py
- tests/marshal/marshal_primitive_test.py
- tests/param/marshal_param_test.py
- tests/profiling/marshal_profiler_test.py
This PR mimics what has been done in #336 for the unmarshaling process.
As for the unmarshaling also in case of the marshaling process we have a good performance improvements.
Raw data: https://gist.github.com/macisamuele/ee3b66176becab678aedf943e7a0e512
* the worst performance improvement is ~61% (if in the branch takes 1 then on master takes 2.58)
* the best performance improvement is ~72% (if in the branch takes 1 then on master takes 3.60)
* the average performance improvement is ~79% (if the branch takes 1 then on master takes 4.89)
> Enhance marshaling performances

- bravado_core/marshal.py
- bravado_core/unmarshal.py
As agreed on #339 we should make sure that we have a single entrypoint to `_decorators.handle_null_value` as it is easy to forget setting the appropriate `is_marshaling_operation` flag.
The goal of this PR is to address this by using partials as unique usage of `_handle_null_value` in the different modules.
> marshal and unmarshal flow uses a flow specific handle_null_value function 

- bravado_core/model.py
- tests/model/is_model_test.py
- tests/model/is_object_test.py
- tests/model/model_discovery_test.py
While testing the library, I've played a bit importint the kubernetes swagger specs ([link](https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.15/api/openapi-spec/swagger.json)).
The specs were selected as a good example of very very big swagger specs.
During the testing I've uncovered an issue related to `is_models` and `is_object` methods.
The method do assume that `x-model` and `title` properties of the object are string, but this is not something that we could actually assume as the specs do not prevent the presence of the attribute as valid object properties.
For example
```yaml
definitions:
model:
properties:
title:
type: string
x-model:
type: string
```
The goal of this PR is to better handle the condition of:
* `x-model` is not a `string`
* `title` is not a `string` …
> Increase resilience of is_model and is_object methods

- tests/model/model_test.py
``tests/model/model_test.py::test_model_delete_property`` test is failing on master.
The issue is most probably caused by some changes on pytest 4.6.x release.
https://github.com/pytest-dev/pytest/pull/5103
In order to get the test green again I've modified it to not use `all` in the assertion
> Fix test failure

- bravado_core/response.py
- tests/response/validate_response_headers_test.py
Previously the header_name was not found in the error, which made it not very informative.
Example:
Before: `None is not of type 'string'`
After: `None is not of type 'string' for header 'X-Request-Id'`
> Provide more useful error message for response header validation.

- bravado_core/spec_flattening.py
- test-data/2.0/models_referenced_by_polymorphic_models/definitions.json
- test-data/2.0/models_referenced_by_polymorphic_models/swagger.json
- tests/spec/Spec/flattened_spec_test.py
Enhancing spec flattening done in #324 (released with bravado-core==5.12.0) did introduce a bug that caused models referenced by discriminated models to not be included in the final spec flattening.
A minimal use-case has been extracted in ` test-data/2.0/models_referenced_by_polymorphic_models/`.
The basic bug was related to the fact that `register_unflattened_models` relied on a _gobal_ variable for the `flattened_models` which was not properly updated after the model discovery.
In order to fix this issue I've made sure that the determination of the already flattened models is done in the `register_unflattened_models` context
> Fix model discovery during flattening

- CHANGELOG.rst
- bravado_core/formatter.py
- bravado_core/spec.py
- docs/source/config.rst
- tests/formatter/to_python_test.py
- tests/formatter/to_wire_test.py
Define a `SwaggerFormat` for the "byte" string format that  base64-encodes binary data to wire and base64-decodes from wire to a Python `bytes` object.
This behavior is not backward-compatible so I added a config option to enable it, disabled by default.
Related: #146
> Add option to automatically encode/decode strings with byte format

- tests/model/model_test.py
- tests/unmarshal/unmarshal_primitive_test.py
- tox.ini
* Add filters for uncaught warnings in tests.
* <strike>Treat unfiltered warnings as test failures.  (Not sure about this change, is it too strict?)</strike> (This caused the Travis build to fail; reverted.)
> Fix test warnings

- bravado_core/model.py
* Document `_json_reference` attribute in `Model` docstring.
* Remove class attributes from `Model.__slots__`; also set `__slots__ = ()` on model subclasses
* Add type hints for `Model._swagger_spec`, `Model._model_spec`, and `Model._json_reference`.
> Model class improvements

- bravado_core/model.py
- tests/model/model_test.py
Model equality check was implemented by ensuring that two objects of the same class and with the same "dict" representation are considered the same.
As far as this definition is valid we might do it a bit better.
Currently, `isinstance` and `issubclass` checks do consider _equivalent_ model types generated by different `bravado_core.spec.Spec` instances if they are created out of the same specs (same url and content).
So what can happen is that
```python
instance1 = spec1.definitions['model1'](...)
instance2 = spec2.definitions['model1']model1(...)
assert isinstance(instance1, instance2.__class__)
assert isinstance(instance2, instance1.__class__)
assert instance1._as_dict() == instance2._as_dict()
assert instance1 == instance2  # This would fail with the currently released bravado-core …
```
> Update Model.__eq__ logic

- tests/spec/Spec/deref_flattened_spec_test.py
Fixes a nondeterministic [unit test failure](https://travis-ci.org/Yelp/bravado-core/jobs/601215889) caused by a buggy test helper function.
> Fix equivalence check in deref_flattened_spec_test.py

- bravado_core/schema.py
`is_list_like` is called by bravado-asyncio, and is the last call it makes that is untyped. Typing it means we can enable `disallow_untyped_calls` in its mpy config.
I'm typing the other two is_* functions as well while I'm at it.
> Add type annotations to is_list_like, is_dict_like, is_ref

- bravado_core/model.py
- bravado_core/operation.py
- bravado_core/resource.py
- bravado_core/security_definition.py
- bravado_core/spec.py
- tests/conftest.py
- tests/operation/equality_test.py
- tests/operation/security_object_test.py
- tests/request/unmarshal_request_test.py
- tests/resource/deepcopy_test.py
- tests/resource/equality_test.py
- tests/spec/Spec/build_test.py
- tests/spec/Spec/deepcopy_test.py
- tests/spec/Spec/equality_test.py
- tests/spec/Spec/get_op_for_request_test.py
A `bravado_core.spec.Spec` instance is currently not deep copiable.
So running something like `deepcopy(Spec.from_dict(<valid_specs>))` results on an unbounded recursion error.
The goal of this PR is to address this issue by defining  the `__deepcopy__` dunder method.
> Ensure that spec is deep copiable

- tests/swagger20_validator/ref_validator_test.py
Tests are currently failing on master
* last green build: https://travis-ci.org/Yelp/bravado-core/jobs/646621656
* last build: https://travis-ci.org/Yelp/bravado-core/jobs/646621656
The difference in the two builds is limited to the `mock` library:
* `mock==3.0.5` in the green build
* `mock==4.0.0` in the failing build
The [following code](https://github.com/testing-cabal/mock/blob/4.0.0/mock/mock.py#L493-L495) is causing the test setup to fail.
The change was introduced by https://github.com/testing-cabal/mock/pull/476/ as part of backporting the "official" `unittest.mock` back into the package.
In order to fix the test we could:
1. modify jsonschema, which does raise the exception in purpose (deprecation related task)
2. not define the `spec` while defining the mock
3. limit `mock` to …
> [Fix tests] Remove spec=Draft4Validator from mock_validator

- bravado_core/operation.py
- bravado_core/resource.py
- bravado_core/spec.py
- tests/conftest.py
- tests/operation/equality_test.py
- tests/resource/equality_test.py
- tests/spec/Spec/equality_test.py
This PR deprecates #363 
As users of the library might be using hashability of `bravado_core.spec.Spec` and we don't have a strong need to have equality checks (other than for testing) I'm proposing to preserve the default equality checks and move the customly defined ones (PR #360) into a different method `is_equal` such that we can have an entry point of equality checks without altering the hashability properties of the objects.
NOTE: In #363 I was trying to define an `__hash__` method were needed.
Unfortunately defining hash functions is not a trivial task as it might be computationally expensive and grows with the size of the specs (which is usually when you'd like to use it even more).
---
From #363
> The issue has been noticed because …
> Replace __eq__ with is_equal to allow hashability

- .travis.yml
- setup.py
- tox.ini
This PR deprecates #362 
More details in https://github.com/Yelp/bravado-core/pull/362#issuecomment-562578356
Note: Test failures are already addressed in #365 .
Even if this will be approved as is I'll wait to have green tests before merging
> Drop python3.5.0 support

- bravado_core/exception.py
- bravado_core/formatter.py
- bravado_core/model.py
- bravado_core/schema.py
- bravado_core/security_definition.py
- bravado_core/security_requirement.py
- bravado_core/spec.py
- bravado_core/swagger20_validator.py
- bravado_core/util.py
- bravado_core/validate.py
- mypy.ini
This PR does extract part of the work done in #314.
Not all the models have yet typing so mypy has been configured to be strict on all the typed modules and more relaxed on the non-typed ones (bravado_core.docstring, bravado_core.model, bravado_core.operation, bravado_core.param, bravado_core.request, bravado_core.resource, bravado_core.response, bravado_core.spec, bravado_core.spec_flattening)
> Enhance typing annotations

- bravado_core/swagger20_validator.py
- test-data/2.0/polymorphic_specs/swagger.json
- tests/model/model_test.py
- tests/response/unmarshal_response_test.py
The goal of this review is to address the validation issue that affects polymorphic models that are nullable (via `x-nullable` field).
In order to better highlight the reported issue I've modified the `polymorphic_specs` to ensure that the operation (endpoint) used for testing does return an object that is not directly the polymorphic model.
The issue was mostly caused by the fact that `discriminator` validation was not using the _usual_ safe check around nullability and so in case of `instance=None` entering `bravado_core.swagger20_validator.discriminator_validator` was not short circuiting and instead trying to extract the discriminator key from instance (which was none) and so leading to `TypeError` being thrown.
Adding the null-gate address the issue an so resolves #359
> Fix issue #359: properly validate nullable polymorphic models

- setup.py
From the msgpack-python pypi page:
> This package is deprecated. Install msgpack instead.
> Use the correct msgpack dependency

- bravado_core/_compat.py
- bravado_core/formatter.py
- bravado_core/model.py
- bravado_core/operation.py
- bravado_core/resource.py
- bravado_core/security_definition.py
- bravado_core/spec.py
- tests/formatter/to_wire_test.py
- tests/operation/equality_test.py
- tests/resource/equality_test.py
- tests/spec/Spec/equality_test.py
While working on a branch related to #370 I've noticed that the implemented equality checks are good but not  enough ;)
Currently the checks are making some assumptions on the state of certain attributes:
* "It is built via Spec.build so we're ignoring it", but it is on the public interface so users might just modify it
* fully skipping the check around resources and operations due to recursive Spec references
* not considering that in the case of `internally_dereference_refs: true` the check (as it was implemented) would have had an unbounded recursion
The goal of this PR is to address those issues (still the checks are not perfect, but they should be more accurate) as well as providing a sort of method documentation.
> Enhance equality checks

- .travis.yml
- tox.ini
The goal of this PR is to address travis configuration warnings (check [here](https://travis-ci.org/Yelp/bravado-core/builds/653928181/config)) as well as ensuring that we're using Python3.7 for the "meta-checks" of the repository.
A bonus added in this PR is related to the addition of [`tox-travis`](https://github.com/tox-dev/tox-travis) dependency that allows us to not define `TOXENV=py` or `TOXENV=py##` to run tests only on the travis provided python version.
> Travis file update: by default use python3.7 and fix travis warnings

- bravado_core/operation.py
- bravado_core/param.py
- bravado_core/resource.py
- mypy.ini
The goal of this PR is to fully type the bravado_core.operation and bravado_core.resource modules.
In order to achieve proper typing I had to update the implementation of the `__repr__` methods as they were returning unicode strings while `object.__repr__` expect strings (this applies only to python 2).
I thought that adding the condition over the python version would be the best way of dealing with the issue instead of dropping an effective (but unsightly) `type: ignore`
> Typing annotations: resource and operation

- bravado_core/model.py
- bravado_core/resource.py
- bravado_core/spec.py
- tests/model/pickling_test.py
- tests/spec/pickling_test.py
The goal of this PR is to fix #370 
In order to make `bravado_core.spec.Spec` pickable I had to define `__getstate__` and `__setstate__` methods into `Spec` and `Resource` class.
The reason of this is that pickling an object usually gets all the object attributes and tries to pickle them:
* `Resource` does define `__dir__` method which confuses the pickling process
* `Spec` needs to deal with the fact that runtime created types (models) are not picklable. In order to make them pickable I'm pickling a representation of the arguments needed to rebuild the type.
Unfortunately this approach has the defect that restoring (unpickling) the object might depend on the version of bravdo_core in use (more importantly on the signature of `create_model_type`.
I think that this is eventually acceptable …
> Pickling support

- requirements-dev.txt
- tox.ini
This fixes the build in the same way I fixed it for bravado. It also makes sure we run mypy as well as tests on Python 3.6 locally, and fixes installation / usage of pre-commit on systems where `python2.7` is not in `/usr/bin`.
> Restrict pytest to <4.7 to fix build, add py36 and mypy to tox envlist

- bravado_core/spec.py
- setup.py
This is kind of a doozy. Basically at some point jsonschema changed some behavior where it will now use the remote resolver logic to get remote jsonschema draft meta-specs. The old logic wouldn't actually work without an http client, which was not required to be set on a `Spec` object. This adds a default client object.
The client object itself is a little strange, because the docstring for the `Spec` type specifies that it should be a `bravado.http_client.HttpClient`. However, depending on that would lead to a circular dependency and untangling that is a lot of work. Instead, I made the most basic type which satisfies the minimal requirements for making this functional, which means creating the `BasicHTTPClient` and `BasicHTTPFuture` types.
> add fallback http client for spec resolution as jsonschema requires it

- bravado_core/spec.py
This adds an option to set the `validate_swagger_spec` default via an environment variable.
The motivation is that we've found that a large amount of time is spent validating swagger specs in certain circumstances (e.g. tests) where it can dramatically increase test timings. Unfortunately, a lot of this validation happens at import time where it's difficult to patch the default via Python code, so we'd like to have the option to do it via environment variable.
> Add option to set validate_swagger_spec default via environment variable
